#!/bin/sh

### Main Commands ###

# Copy
alias cp='cp -iv'
alias cpd='cp -ivr'

# Grep
alias grep='grep --color=auto'

# Make dir
alias mkdir='mkdir -pv'

# Move
alias mv='mv -iv'

# Remove
alias rm='rm -vI --preserve-root'
alias rmd='rm -vIr --preserve-root'

### Replace Commands ###

# Replace "cat" to "bat"
alias cat='bat'

# Replace "ls" to "exa"
alias ls='eza -F --color=always --icons --group-directories-first'
alias la='eza -aF --color=always --icons --group-directories-first'
alias ll='eza -lHF --color=always --icons --group-directories-first'
alias lla='eza -alHF --color=always --icons --group-directories-first'
alias lt='eza -aT --color=always --icons --group-directories-first -L=1'

### Software ###

# Applications
alias v="$EDITOR"

# Git

# Hyprland 
alias wkill='hyprctl kill'

# Pacman
alias p='pacman'                               # pacman shortcut
alias pinstall='pacman -S'                     # pacman install pkgs
alias psyyu='pacman -Syyu'                     # refresh pkglist & update standard pkgs
alias punlock='rm -i /var/lib/pacman/db.lck'   # remove pacman lock file
alias porphan='pacman -Rns $(pacman -Qtdq)'    # remove orphaned pkgs
alias pwhere='pacman -Qs'                      # search installed pkgs

# Paru
alias pa='paru'                                # paru shortcut
alias pasua='paru -Sua'                        # update pkgs from AUR
alias update='paru -Syu'                       # update all pkgs

# Systemd
alias rfoot='systemctl --user restart foot-server.service'
alias remacs='systemctl --user restart emacs.service'

